### ISSUE TITLE
Unpinned networkx giving troubles on PhenoMeNal Galaxy startup of older images (including last release)

### ISSUE THREAD

**Issue by pcm32** [ISA-tools/isatools-core#7]
Currently networkx dependency is unpinned, producing the following issue when starting Galaxy, probably due to a newer networkx version requiring a newer decorate version:

```
Exception:
Traceback (most recent call last):
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 521, in _prepare_file
    req_to_install.check_if_exists()
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1036, in check_if_exists
    self.req.name
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 558, in get_distribution
    dist = get_provider(dist)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 432, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (decorator 4.0.2 (/galaxy/.venv/lib/python2.7/site-packages), Requirement.parse('decorator>=4.1.0'), set(['networkx']))
```

Could we pin the versions of networkx and six, in particular to a version of networkx that doesn't require decorator above 4.0.2?

Thanks!

**Comment by djcomlab** [comment]
Yep! Sorry, didn't see this issue until you brought it up on the PhenoMeNal call. Will fix this ASAP.

**Comment by djcomlab** [comment]
I think this must be because Galaxy is uses the PyPI package, which indeed does not pin the dependencies. Actually, I did already pin the requirements in `requirements-galaxy.txt`.

To confirm, the pins are on:
```
networkx==2.0
six==1.9.0
```
But `networkx` 2.0 or newer requires `decorator>=4.1.0`. I'll try `isa-rwval` with `networkx==1.11` which only requires `decorator>=3.4.0`.

Would it be such a big deal to upgrade the pin in Galaxy's requirements?

**Comment by djcomlab** [comment]
@pcm32 I've downgraded the `networkx` version in the develop branch here. Can you try it out with Galaxy to check compatibility? If it works OK I can build the universal wheels and upload a new version to PyPI.

**Comment by pcm32** [comment]
Great thanks!

**Comment by djcomlab** [comment]
This was fixed for Galaxy 17.09, but broken again in for the Galaxy 18.01 upgrade.

**Comment by djcomlab** [comment]
Just trying out the upgrade of `six` and will push a new release of `isa-rwval` for the phenomenal Galaxy 18.01 PR.

**Comment by djcomlab** [comment]
Fixed in latest commit, closing...
